### ISSUE TITLE
Spanish translation not available.

### ISSUE THREAD

**Issue by Jorge-GD** [breatheco-de/starwars-data-model-typeorm-node#1]
Greetings,

I was checking this project and was surprised that when change the language to Spanish, it doesn't have a file.

![image](https://user-images.githubusercontent.com/84985189/125762568-5a559396-8f38-40dc-a5cd-a81f236a9c67.png)

Actually there is no README.es.md, that's why it gives the error.

I'm attaching a quick translation I made, in case you want to add it instead of removing the button.

Regards

[README.es.md](https://github.com/breatheco-de/starwars-data-model-typeorm-node/files/6821805/README.es.md)

**Comment by alesanchezr** [comment]
Wow thank you Jorge for this translation! And for reporting the bug. I added the file to the repo.

Next time, if you want to contribute you can do a `pull request` instead, that way you get the credit for the contribution, its basically as easy as this.

1. Create the fork
2. A fork basically creates a copy of the repo under your ownership.
3. Update your forked repo with the Spanish readme (now that you have access)
4. Create a pull request.
